application: shareflu
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"

handlers:

# index files
- url: /(.+)/
  static_files: build/\1/index.html
  upload: build/(.+)/index.html

- url: /
  static_dir: build
  expiration: "0s"


